/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ricoh.es;

/**
 *
 * @author Agustí
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelProp = new javax.swing.JPanel();
        jButtonopenProp = new javax.swing.JButton();
        jButtonUploadProp = new javax.swing.JButton();
        jPanelPlatforms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlatforms = new javax.swing.JTable();
        jProgressBarUpload = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTestProjects = new javax.swing.JComboBox();
        jComboBoxTestPlan = new javax.swing.JComboBox();
        jPanelExec = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldExcelToTestlink = new javax.swing.JTextField();
        jButtonUploadExcelToTestLink = new javax.swing.JButton();
        jButtonExecuteExcelTotestLink = new javax.swing.JButton();
        jProgressBarExelToTestLink = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListExecuteResults = new javax.swing.JList();
        jButtonFilter = new javax.swing.JButton();
        jLabelLogs = new javax.swing.JLabel();
        jButtonUploadExel = new javax.swing.JButton();
        jComboBoxLastExecution = new javax.swing.JComboBox();
        jButtonCheckExcel = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableToExecute = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUTOMATION TESTLINK");
        setFocusCycleRoot(false);

        jButtonopenProp.setText("OPEN PROPERTIES");
        jButtonopenProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopenPropActionPerformed(evt);
            }
        });

        jButtonUploadProp.setText("UPLOAD PROPERTIES");
        jButtonUploadProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadPropActionPerformed(evt);
            }
        });

        jPanelPlatforms.setBorder(javax.swing.BorderFactory.createTitledBorder("PLATFORMS"));

        jTablePlatforms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePlatforms);

        javax.swing.GroupLayout jPanelPlatformsLayout = new javax.swing.GroupLayout(jPanelPlatforms);
        jPanelPlatforms.setLayout(jPanelPlatformsLayout);
        jPanelPlatformsLayout.setHorizontalGroup(
            jPanelPlatformsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelPlatformsLayout.setVerticalGroup(
            jPanelPlatformsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlatformsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("PROJECTS:");

        jLabel2.setText("TESTPLANTS:");

        jComboBoxTestProjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTestProjects.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTestProjectsItemStateChanged(evt);
            }
        });

        jComboBoxTestPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTestPlan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTestPlanItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTestProjects, 0, 316, Short.MAX_VALUE)
                    .addComponent(jComboBoxTestPlan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTestProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTestPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPropLayout = new javax.swing.GroupLayout(jPanelProp);
        jPanelProp.setLayout(jPanelPropLayout);
        jPanelPropLayout.setHorizontalGroup(
            jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPropLayout.createSequentialGroup()
                        .addGroup(jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPropLayout.createSequentialGroup()
                                .addComponent(jButtonopenProp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUploadProp))
                            .addGroup(jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jProgressBarUpload, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addComponent(jPanelPlatforms, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 670, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPropLayout.setVerticalGroup(
            jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonopenProp)
                    .addComponent(jButtonUploadProp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPlatforms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PROPERTIES", jPanelProp);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.1);
        jSplitPane1.setToolTipText("");

        jTextFieldExcelToTestlink.setText("jTextField1");
        jTextFieldExcelToTestlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExcelToTestlinkActionPerformed(evt);
            }
        });

        jButtonUploadExcelToTestLink.setText("...");
        jButtonUploadExcelToTestLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadExcelToTestLinkActionPerformed(evt);
            }
        });

        jButtonExecuteExcelTotestLink.setText("EXECUTE");
        jButtonExecuteExcelTotestLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecuteExcelTotestLinkActionPerformed(evt);
            }
        });

        jProgressBarExelToTestLink.setForeground(new java.awt.Color(255, 0, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("EXECUTE RESULTS"));

        jListExecuteResults.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListExecuteResults);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonFilter.setText("FILTER");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jLabelLogs.setText("jLabel3");

        jButtonUploadExel.setText("UPLOAD EXCEL");
        jButtonUploadExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadExelActionPerformed(evt);
            }
        });

        jComboBoxLastExecution.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EXECUTE AND REMOVE LAST EXECUTION", "ONLY EXECUTE", "REMOVE LAST EXECUTION AND EXECUTE", "REMOVE LAST EXECUTION","CHECK EXECUTION" }));

        jButtonCheckExcel.setText("CHECK EXCEL");
        jButtonCheckExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldExcelToTestlink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUploadExcelToTestLink))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonUploadExel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonExecuteExcelTotestLink)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                                .addGap(145, 145, 145)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonCheckExcel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonFilter))
                                    .addComponent(jComboBoxLastExecution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jProgressBarExelToTestLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExcelToTestlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUploadExcelToTestLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFilter)
                            .addComponent(jButtonUploadExel)
                            .addComponent(jButtonCheckExcel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExecuteExcelTotestLink)
                            .addComponent(jLabelLogs)
                            .addComponent(jComboBoxLastExecution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBarExelToTestLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel2);

        jTableToExecute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableToExecute);

        jSplitPane1.setRightComponent(jScrollPane5);

        javax.swing.GroupLayout jPanelExecLayout = new javax.swing.GroupLayout(jPanelExec);
        jPanelExec.setLayout(jPanelExecLayout);
        jPanelExecLayout.setHorizontalGroup(
            jPanelExecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        jPanelExecLayout.setVerticalGroup(
            jPanelExecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("EXCEL TO TESTLINK", jPanelExec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonopenPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopenPropActionPerformed
        // TODO add your handling code here:
        Buttons.openProp();
    }//GEN-LAST:event_jButtonopenPropActionPerformed

    private void jButtonUploadPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadPropActionPerformed
        // TODO add your handling code here:
        Buttons.initializeProp();
    }//GEN-LAST:event_jButtonUploadPropActionPerformed

    private void jComboBoxTestProjectsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTestProjectsItemStateChanged
        // TODO add your handling code here:
        Buttons.projecsItemStateChanged();
    }//GEN-LAST:event_jComboBoxTestProjectsItemStateChanged

    private void jComboBoxTestPlanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTestPlanItemStateChanged
        // TODO add your handling code here:
        Buttons.testPlanItemStateChanged();
    }//GEN-LAST:event_jComboBoxTestPlanItemStateChanged

    private void jButtonUploadExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadExelActionPerformed
        // TODO add your handling code here:
        Buttons.uploadExcel();
    }//GEN-LAST:event_jButtonUploadExelActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        // TODO add your handling code here:
        Buttons.filter();
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonExecuteExcelTotestLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecuteExcelTotestLinkActionPerformed
        // TODO add your handling code here:
        Buttons.executeExcelToTestLink();
    }//GEN-LAST:event_jButtonExecuteExcelTotestLinkActionPerformed

    private void jButtonUploadExcelToTestLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadExcelToTestLinkActionPerformed
        // TODO add your handling code here:
        Buttons.uploadExcelToTestLink();
    }//GEN-LAST:event_jButtonUploadExcelToTestLinkActionPerformed

    private void jTextFieldExcelToTestlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExcelToTestlinkActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldExcelToTestlinkActionPerformed

    private void jButtonCheckExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckExcelActionPerformed
        // TODO add your handling code here:
        Buttons.checkExcel();
    }//GEN-LAST:event_jButtonCheckExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Panel p = new Panel();
                UploadProp.initialize( p);
       
                p.setVisible(true);
                UploadProp.initialize();
            }
        });
        
    }
/*
                javax.swing.JTextField jTextFieldExcelTotestLink,
            javax.swing.JProgressBar jProgressBarExelToTestLink,
            javax.swing.JTextArea jTextAreaExcelToTestlink){
    
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckExcel;
    protected javax.swing.JButton jButtonExecuteExcelTotestLink;
    protected javax.swing.JButton jButtonFilter;
    protected javax.swing.JButton jButtonUploadExcelToTestLink;
    protected javax.swing.JButton jButtonUploadExel;
    protected javax.swing.JButton jButtonUploadProp;
    protected javax.swing.JButton jButtonopenProp;
    protected javax.swing.JComboBox jComboBoxLastExecution;
    protected javax.swing.JComboBox jComboBoxTestPlan;
    protected javax.swing.JComboBox jComboBoxTestProjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabelLogs;
    protected javax.swing.JList jListExecuteResults;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelExec;
    private javax.swing.JPanel jPanelPlatforms;
    private javax.swing.JPanel jPanelProp;
    protected javax.swing.JProgressBar jProgressBarExelToTestLink;
    protected javax.swing.JProgressBar jProgressBarUpload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JTable jTablePlatforms;
    protected javax.swing.JTable jTableToExecute;
    protected javax.swing.JTextField jTextFieldExcelToTestlink;
    // End of variables declaration//GEN-END:variables
}
